# Generated by Django 5.2.13 on 2026-06-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinvertory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarInvertory',
            new_name='CarInventory',
        ),
        migrations.RemoveField(
            model_name='carinventory',
            name='cars_volue',
        ),
        migrations.AddField(
            model_name='carinventory',
            name='cars_value',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
